There are no missing values and no duplicates, this notebook is  important because real data cleaning also includes fixing invalid values.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/Base.csv")
print(df.shape)
df.head()

(1000000, 32)

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,payment_type,zip_count_4w,...,has_other_cards,proposed_credit_limit,foreign_request,source,session_length_in_minutes,device_os,keep_alive_session,device_distinct_emails_8w,device_fraud_count,month
0,0,0.3,0.986506,-1,25,40,0.006735,102.453711,AA,1059,...,0,1500.0,0,INTERNET,16.224843,linux,1,1,0,0
1,0,0.8,0.617426,-1,89,20,0.010095,-0.849551,AD,1658,...,0,1500.0,0,INTERNET,3.363854,other,1,1,0,0
2,0,0.8,0.996707,9,14,40,0.012316,-1.490386,AB,1095,...,0,200.0,0,INTERNET,22.730559,windows,0,1,0,0
3,0,0.6,0.475100,11,14,30,0.006991,-1.863101,AB,3483,...,0,200.0,0,INTERNET,15.215816,linux,1,1,0,0
4,0,0.9,0.842307,-1,29,40,5.742626,47.152498,AA,2339,...,0,200.0,0,INTERNET,3.743048,other,0,1,0,0

In [4]:
missing = pd.DataFrame({"Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().mean()*100,2)
})
missing

                                  Missing Values  Percentage
fraud_bool                                     0         0.0
income                                         0         0.0
name_email_similarity                          0         0.0
prev_address_months_count                      0         0.0
current_address_months_count                   0         0.0
customer_age                                   0         0.0
days_since_request                             0         0.0
intended_balcon_amount                         0         0.0
payment_type                                   0         0.0
zip_count_4w                                   0         0.0
velocity_6h                                    0         0.0
velocity_24h                                   0         0.0
velocity_4w                                    0         0.0
bank_branch_count_8w                           0         0.0
date_of_birth_distinct_emails_4w               0         0.0
employment_status                              0         0.0
credit_risk_score                              0         0.0
email_is_free                                  0         0.0
housing_status                                 0         0.0
phone_home_valid                               0         0.0
phone_mobile_valid                             0         0.0
bank_months_count                              0         0.0
has_other_cards                                0         0.0
proposed_credit_limit                          0         0.0
foreign_request                                0         0.0
source                                         0         0.0
session_length_in_minutes                      0         0.0
device_os                                      0         0.0
keep_alive_session                             0         0.0
device_distinct_emails_8w                      0         0.0
device_fraud_count                             0         0.0
month                                          0         0.0

In [5]:
print("Duplicate rows :", df.duplicated().sum())

Duplicate rows : 0

In [6]:
unique = pd.DataFrame({"Column": df.columns,"Unique Values": df.nunique().values})
unique

                              Column  Unique Values
0                         fraud_bool              2
1                             income              9
2              name_email_similarity         998861
3          prev_address_months_count            374
4       current_address_months_count            423
5                       customer_age              9
6                 days_since_request         989330
7             intended_balcon_amount         994971
8                       payment_type              5
9                       zip_count_4w           6306
10                       velocity_6h         998687
11                      velocity_24h         998940
12                       velocity_4w         998318
13              bank_branch_count_8w           2326
14  date_of_birth_distinct_emails_4w             40
15                 employment_status              7
16                 credit_risk_score            551
17                     email_is_free              2
18                    housing_status              7
19                  phone_home_valid              2
20                phone_mobile_valid              2
21                 bank_months_count             33
22                   has_other_cards              2
23             proposed_credit_limit             12
24                   foreign_request              2
25                            source              2
26         session_length_in_minutes         994887
27                         device_os              5
28                keep_alive_session              2
29         device_distinct_emails_8w              4
30                device_fraud_count              1
31                             month              8

In [7]:
special_cols = [ "prev_address_months_count","current_address_months_count","bank_months_count",
                "session_length_in_minutes","device_distinct_emails_8w","credit_risk_score"]
for col in special_cols:
    print(col)
    print((df[col] == -1).sum())
    print()

prev_address_months_count
712920

current_address_months_count
4254

bank_months_count
253635

session_length_in_minutes
2015

device_distinct_emails_8w
359

credit_risk_score
488

In [13]:
import numpy as np
special_cols = ["prev_address_months_count","current_address_months_count","bank_months_count",
                "session_length_in_minutes","device_distinct_emails_8w","credit_risk_score"]
for col in special_cols:
    df[col] = df[col].replace(-1, np.nan)

In [14]:
for col in special_cols:
    df[col] = df[col].fillna(df[col].median())

In [15]:
for col in special_cols:
    print(col, (df[col] == -1).sum())

prev_address_months_count 0
current_address_months_count 0
bank_months_count 0
session_length_in_minutes 0
device_distinct_emails_8w 0
credit_risk_score 0

In [16]:
df[special_cols].isnull().sum()

prev_address_months_count       0
current_address_months_count    0
bank_months_count               0
session_length_in_minutes       0
device_distinct_emails_8w       0
credit_risk_score               0
dtype: int64

In [17]:
print(df.shape)

(1000000, 32)

In [18]:
df.to_csv("../data/processed/fraud_detection_cleaned.csv", index=False)
print("Dataset saved successfully.")

Dataset saved successfully.

# Data Cleaning Completed Successfully

-Loaded the raw fraud detection dataset.
-Verified the dataset dimensions and data types.
-Checked for missing values across all columns.
-Confirmed that no duplicate records were present.
-Identified special placeholder values (-1) in selected columns.
-Replaced -1 values with NaN and imputed them using the median of the respective columns.
-Verified that no missing values or invalid placeholder values remained.
-Confirmed the dataset is clean and ready for analysis.
-Saved the cleaned dataset for use in the next notebook.

# Final Dataset Information
Rows: 1,000,000
Columns: 32
Missing Values: 0
Duplicate Rows: 0
Invalid (-1) Values: Replaced with median values